### ISSUE TITLE
Update dehalo_alpha

### ISSUE THREAD

**Issue by Setsugennoao** [Irrational-Encoding-Wizardry/vs-dehalo#11]
From Zewia:

- [x] what do you think about adding an iterations parameter to dehalo_alpha

i find that applying the filter multiple times at weaker strengths is usually better than one call at a strong strength

**Comment by LightArrowsEXE** [comment]
I'd also like to see a `List[float]` for `rx`/`ry` so we can determine strength on a per-plane basis. Right now we need to call the function twice, once with `planes=0` and once with `planes=[1, 2]`.

**Comment by Setsugennoao** [comment]
Added both suggestions. Zewia's: https://github.com/Irrational-Encoding-Wizardry/vs-dehalo/commit/97f8dd708c5ea546ab9b4c71b8529a57278d2f05, Light's: https://github.com/Irrational-Encoding-Wizardry/vs-dehalo/commit/f262402823c85b4f0cf21d499eebfc6129a760fe.
