### ISSUE TITLE
fine_dehalo: low/highsens don't do anything

### ISSUE THREAD

**Issue by LightArrowsEXE** [Irrational-Encoding-Wizardry/vs-dehalo#3]
Been trying out the low/highsens and comparing the results. Neither seem to be altering the picture at all.

src

![image](https://user-images.githubusercontent.com/42927908/174455632-1be4f748-6caf-4b71-ac5b-4c5891da0224.png)

vsdh.fine_dehalo(src, src, rx=2, ry=2, thmi=40, thma=256, showmask=1)

![image](https://user-images.githubusercontent.com/42927908/174455637-610b1dad-d195-430a-b930-92f76e2a2135.png)

vsdh.fine_dehalo(src, src, rx=2, ry=2, thmi=40, thma=256, highsens=300, showmask=1)

![image](https://user-images.githubusercontent.com/42927908/174455640-9ab31136-4ce8-4dd1-8ea1-db7a8ac73f57.png)

**Comment by Setsugennoao** [comment]
The parameters do in fact affect the mask, just dehalo_alpha's though.
What you're outputting, however, is fine_dehalo's mask.
