### ISSUE TITLE
smooth_dering mask output

### ISSUE THREAD

**Issue by nobananasforyou** [Irrational-Encoding-Wizardry/vs-dehalo#37]
G'day!

I tested smooth_dering on a source and it behaves differently on an 8bit depth compared to 16bit, the changes can be observed in the output mask. Here's an image comparison along with a test script.

Original Image:
![org](https://cdn.discordapp.com/attachments/1006843951480836207/1083412380140195901/org.png)

Image Comparison:
https://slow.pics/c/Z1anhLHV

Test Script:
s1 = depth(src, 8)
s1 = smooth_dering(s1, mrad=1, msmooth=3, minp=2, mthr=40, darkthr=0, contra=0, show_mask=True)
s2 = depth(src, 16)
s2 = smooth_dering(s2, mrad=1, msmooth=3, minp=2, mthr=40, darkthr=0, contra=0, show_mask=True)

Kind Regards

**Comment by Setsugennoao** [comment]
Fixed in https://github.com/Irrational-Encoding-Wizardry/vs-dehalo/commit/21bcfc0c85c2ca7606f095eb98606877900165c0
