### ISSUE TITLE
YAHRmask and Documentation

### ISSUE THREAD

**Issue by nobananasforyou** [Irrational-Encoding-Wizardry/vs-dehalo#6]
G'day!

1  - Could you please add YAHRmask https://github.com/WolframRhodium/muvsfunc/blob/master/muvsfunc.py#L5198 to vs-dehalo? There's YARHmod as well. However, from my tests YAHRmask performs better than YAHR and YARHmod. I also found a bug in YAHRmask and it has yet to be resolved #https://github.com/WolframRhodium/muvsfunc/issues/45
2 - Can you please documentation on how to use these functions with some examples in vs-dehalo's repo.
3 - How is vs-dehalo's edgecleaner different from haf's edgecleaner? I just want to understand what it does.  

Thank you.

**Comment by Setsugennoao** [comment]
Hello, and thanks for opening this issue.

1. vs-dehalo's YAHR already merges YAHR, YAHRMod and YAHRMask in one function.
  I've added the `show_mask` parameter, and if set to True it will yield the mask, just like YAHRMask.
  That is if you want to use it with other functions.
2. Please open another issue for documentation.
3. For starters, just like all functions in vs-dehalo, it supports float32 input and chroma processing, then it has a more robust mask and even lets you pass a custom mask class istance, that you can get from vs-mask.

**Comment by Setsugennoao** [comment]
I just checked and yes, muvsfunc's YAHRMask has that problem, however vs-dehalo doesn't, so i'm going to close the issue.

Thanks again!

**Comment by nobananasforyou** [comment]
Thank you!
